### ISSUE TITLE
Do you know if there is a plan for sharing a demo code ?

### ISSUE THREAD

**Issue by myeongjun-ds** [MCG-NJU/STMixer#3]
Thank you for sharing your excellent works !

I have two questions !
1. Do you know if there is a plan for sharing a demo code ?
2. In the inference, the model needs bboxes and labels. Do you think it's necessary ?
  - In the inference, usually the model don't know about the gt labels.

**Comment by atao99** [comment]
Hi, 

Sorry, there is no plan to release the demo code in the short term due to my limited bandwidth.

In the inference, we use the same dataset code as training for convenience, but the gt boxes and labels are actually not used.

Thank you for your attention.

Best wishes.

**Comment by myeongjun-ds** [comment]
Thank you for comments !

You mean, Is it ok to put None value in gt boxes and labels ?

Thank you !

**Comment by atao99** [comment]
For inference, yes.

**Comment by myeongjun-ds** [comment]
Thank you !
